trigger:
- main

stages:

# ==========================================
# BUILD
# ==========================================
- stage: Build
  displayName: Build

  jobs:
  - job: BuildJob

    pool:
      vmImage: ubuntu-latest

    steps:

    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '21'
        jdkArchitectureOption: x64
        jdkSourceOption: PreInstalled

    - task: Maven@4
      displayName: Build Project
      inputs:
        mavenPomFile: pom.xml
        goals: 'clean package'
        publishJUnitResults: true

# ==========================================
# SONARCLOUD
# ==========================================
- stage: CodeQuality
  displayName: SonarCloud Analysis

  dependsOn: Build

  jobs:
  - job: Sonar

    pool:
      vmImage: ubuntu-latest

    steps:

    - task: SonarCloudPrepare@3
      inputs:
        SonarCloud: 'SonarCloud-ServiceConnection'
        organization: 'your-org'
        scannerMode: 'Maven'
        projectKey: 'quiz-app'
        projectName: 'quiz-app'

    - task: Maven@4
      inputs:
        mavenPomFile: pom.xml
        goals: 'verify sonar:sonar'

    - task: SonarCloudPublish@3
      inputs:
        pollingTimeoutSec: '300'

# ==========================================
# DEPLOY
# ==========================================
- stage: Deploy
  displayName: Production Deployment

  dependsOn: CodeQuality

  jobs:

  - deployment: DeployToProd

    environment: Production

    pool:
      vmImage: ubuntu-latest

    strategy:
      runOnce:
        deploy:

steps:
- script: echo Hello